### PR TITLE
Logo Design Contribution 

### PR DESCRIPTION
**Pull request by ihtiht**
I changed the old logo. I also added the logotype version to the readme file.

### CODE REVIEW

**Comment by kurtextrem** [comment]
Hi @ihtiht, sorry for letting you wait so long.

I really love the logo and I will definitely use it from now on, however in the horizontal version, the font type looks a bit lost in my opinion. The logo looks modern, clean, while the font looks old-ish (western style). What do you think?

**Comment by ihtiht** [comment]
You may be right, my friend. Actually the font is characteristic. Why do not you choose a font [here](https://www.dafont.com/theme.php?cat=501&text=Improved+For+Instagram&fpp=50 )? So you choose the one that works best for you. I apply the font you choose.

**Comment by kurtextrem** [comment]
I like this one a lot: https://www.dafont.com/moderna.font?fpp=50&text=Improved+For+Instagram however unsure about license.
https://www.dafont.com/mixmodern.font?fpp=50&text=Improved+For+Instagram as an alternative

**Comment by ihtiht** [comment]
I applied the font you requested and sent a new PR. https://github.com/kurtextrem/Improved-for-Instagram/pull/44

**Comment by kurtextrem** [comment]
Cheers!! 🎊

**Pull request closed without merging**
