### PR TITLE
Add night mode

### PR DESCRIPTION
**Pull request by KLVN**
Preview

ToDo
- [x] Main feed
- [x] Profile
- [x] Post viewer (standalone)
- [x] Post viewer (popup)
- [ ] Searchbar
- [ ] Search results: Instagrams appends a class to a hovered list-item, instead of using `:hover`
- [ ] Search results: white arrow
- [ ] Notifications: drop-down menu
- [ ] Notifications: icons are currently inverted and look grey-ish
- [ ] _Improved Layout for IG_ pages
- [ ] Settings
- [ ] Explore
- [ ] Modals/Popovers (people who liked, views and some more hidden ones)
- [ ] Missing OS X scrollbar when using standalone post viewer
- [ ] Cleanup
- [ ] ...

### CODE REVIEW

**Comment by kurtextrem** [comment]
Nice!

By the way, what would you prefer: A simple toggle for night mode (perma on/off), or the ability to enter an hour to set when it should get enabled/disabled?

**Comment by KLVN** [comment]
I think a permanent option would be better than a dynamic one, because you get used to a specific design after a while and daily changes would interrupt this process. Although it would be pretty crazy, if it fades between black and white, depending on sunrise and sunset, but this is just a gimmick and would blow up this extension :D

**Comment by kurtextrem** [comment]
I guess I'll go with permanent option and dynamic one, as I prefer the latter :) 
As `night.css` is loaded slightly after the main css anyway, we could add transitions nevertheless. A `transition: filter 500ms ease-out, background-color 500ms ease-out, color 500ms ease-out` or so should do?

**Comment by KLVN** [comment]
Implementing both is even better :D
A transition will be necessary, as there is a (very) small white flickering until `night.css` is loaded.

**Comment by kurtextrem** [comment]
My offer still holds true: I can merge this PR and add you to the original repo as contributor, so you can commit directly :D

**Comment by KLVN** [comment]
I really appreciate it, but I'll just keep opening PR's and having someone to check over the code, before things get messed up :D
(Do I have to open a new PR every time, or can I push new commits to this PR, even if you already merged some code before?)

**Comment by kurtextrem** [comment]
So I've released v2.5 with this PR in it :)

**Comment by kurtextrem** [comment]
I found this article interesting: https://medium.com/@mwichary/dark-theme-in-a-day-3518dde2955a

Especially the following:
```css
img {
  mix-blend-mode: multiply;
}
html[data-theme='dark'] img {
  filter: invert(100%) hue-rotate(180deg);
  mix-blend-mode: screen;
}
```

**Pull request closed without merging**
